### ISSUE TITLE
gearpump use in java

### ISSUE THREAD

**Issue by xyalan** [intel-hadoop/gearpump#673]
I have java application, and wanna use gearpump.Gearpump written in scala，so I guessed that  can use in java.

I configured maven from [maven](http://www.gearpump.io/site/downloads/downloads/#maven), but it could not resolve dependencies. When I ran `mvn clean install`, here some errors:

```
[ERROR] Failed to execute goal on project wordcout: Could not resolve dependencies for project com.hialan.gearepum-samples:wordcout:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: com.github.intel-hadoop:gearpump-core_2.11:jar:0.3.1, com.github.intel-hadoop:gearpump-streaming_2.11:jar:0.3.1, com.github.intel-hadoop:gearpump-rest_2.11:jar:0.3.1, com.github.intel-hadoop:gearpump-external-kafka_2.11:jar:0.3.1, com.github.intel-hadoop:gearpump-experiments-distributedshell_2.11:jar:0.3.1: Could not find artifact com.github.intel-hadoop:gearpump-core_2.11:jar:0.3.1 in releases-oss.sonatype.org (http://oss.sonatype.org/content/repositories/releases/) -> [Help 1]
```
How do I solve this problem?Thanks.

**Comment by clockfly** [comment]
Thanks for reporting,

After checking the sonatype, seems the public artifact are not published successfully. 
https://oss.sonatype.org/content/repositories/releases/com/github/intel-hadoop/gearpump-streaming_2.11/

We are working on solving it.

In the mean while, if you want to try this out asap, you can download the source code of 0.3.1 from
https://github.com/intel-hadoop/gearpump/tree/0.3.1

and then publish it to local maven repo
```
sbt publishLocal
```

**Comment by clockfly** [comment]
Now, the maven repo is fixed.

Check
https://oss.sonatype.org/content/repositories/releases/com/github/intel-hadoop/gearpump-core_2.11/

**Comment by xyalan** [comment]
Yes, core、streaming could resolve,but still some dependencies could not resolve.Like:
```
com.github.patriknw:akka-data-replication_2.11:jar:0.7,om.github.intel-hadoop:gearpump-rest_2.11:jar:0.3.2, com.github.intel-hadoop:gearpump-experiments-distributedshell_2.11:jar:0.3.2
```

From [patriknw](https://github.com/patriknw/akka-data-replication),I added patriknw repo to pom.Now following dependencies could not resolve:
``` 
The following artifacts could not be resolved: com.github.intel-hadoop:gearpump-rest_2.11:jar:0.3.2, com.github.intel-hadoop:gearpump-experiments-distributedshell_2.11:jar:0.3.2
```

BTW, How to use in java?Have Java AP?Thanks.

**Comment by clockfly** [comment]
Oh, Alan,

We renamed the rest to services, experiments-distributedshel to distributedshell.
I will update the http://www.gearpump.io/site/downloads/downloads/#maven to reflect the changes.

**Comment by clockfly** [comment]
You can remove lines about distributedshell and rest.
I have updated the doc under http://www.gearpump.io/site/downloads/downloads/#maven

It should be easy for you to write an app in java.

Here is a quick tutorial, 
Take wordcount as an example:
(source code: https://github.com/intel-hadoop/gearpump/tree/master/examples/streaming/wordcount/src/main/scala/org/apache/gearpump/streaming/examples/wordcount)

The WordCount contains two processor, split processor, and sum processor.
split processor will split line to word, and sum processor will count each word.

1. You can write Split and Sum in java, by extending abstract class org.apache.gearpump.streaming.task.Task.

When you have imported the maven dependencies, you should be able to see the interface of Task in IDE like eclipse.

2. After step2, you need to write a small glue code in scala to define the DAG, like 
https://github.com/intel-hadoop/gearpump/blob/master/examples/streaming/wordcount/src/main/scala/org/apache/gearpump/streaming/examples/wordcount/WordCount.scala

Since most user logic is defined in Processor,  so step2(currently in scala) is relative small.

3. Mix-compile scala and java is easy. For example, we also have java code at 
https://github.com/intel-hadoop/gearpump/tree/master/core/src/main/java/org/apache/gearpump

4. Please see whether you this works. If you still need help, I can write a project template to show you how to do this.

**Comment by xyalan** [comment]
Thanks for helping.

Yes, I'm trying to write wordcount app in java reference [how_to_write_a_streaming_application](http://www.gearpump.io/site/0.3/how_to_write_a_streaming_application/),Task and Taskactor are the same?

**Comment by clockfly** [comment]
@xyalan 

I am sorry, the document is a little out of date, I will update them.
You should use Task. Please refer to the source code of wordcount:
https://github.com/intel-hadoop/gearpump/tree/master/examples/streaming/wordcount/src/main/scala/org/apache/gearpump/streaming/examples/wordcount

They are the most up-to-date reference.

**Comment by clockfly** [comment]
Thanks for reporting this, the document is now updated.
http://www.gearpump.io/site/0.3/how_to_write_a_streaming_application/

**Comment by xyalan** [comment]
Thanks.I'm trying.

**Comment by xyalan** [comment]
I wrote [WordCount](https://github.com/intel-hadoop/gearpump/blob/master/examples/streaming/wordcount/src/main/scala/org/apache/gearpump/streaming/examples/wordcount/WordCount.scala) in java and got some errors.
 Can you write WordCount in java to show you how to do this?Thanks.

**Comment by clockfly** [comment]
Ok, I am writing a template project.

**Comment by clockfly** [comment]
@xyalan 

Please check the template project under https://github.com/gearpump/gearpump-java-example

All in java.

**Comment by xyalan** [comment]
@clockfly 
Thank you so much for helping.I can try to write an app in java now.

**Comment by clockfly** [comment]
Great! :)

Thank you for finding so many document bugs, I have fixed all these document issue on gearpump.io

**Comment by clockfly** [comment]
Mark this as fixed.
