### ISSUE TITLE
Add a default implementation for Kafka Producer

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#728]
Requirements:
1. Need for use to construct (wrap the configuration steps)
2. Expose state timestamp. (To handle out of order message)

This links with #694, #726

**Comment by whjiang** [comment]
I will suggest following for this kafka work:
1. for configuration (including broker and topic), allow user to specify it in multiple ways instead of just KafkaConfig. 
2. make kafka support complete: support both read from kafka queue and write to kafka queue.
3. unify the terms we used: source, sink, producer, consumer...

**Comment by whjiang** [comment]
I will suggest following conventions for implementing in/out connectors:
1. Naming convention:
   a. XXXSource for IN connector (e.g. KafkaSource, HBaseSource)
   b. XXXSink for OUT connector (e.g. KafkaSink, HBaseSink)
2. All these in/out connectors shall be derived from Task class to simplify usage.
3. All these in/out connectors shall follow natural/native way for configuration. E.g. for HBase, HBaseConfiguration (hbase-site.xml or constructing HBaseConfiguration using code) is preferred over using UserConfig directly.

**Comment by manuzhang** [comment]
fixed in #1115
